# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/backbones.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/backbones.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x16protos/backbones.proto\"h\n\x08\x42\x61\x63kBone\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x1d\n\x0euse_pretrained\x18\x02 \x01(\x08:\x05\x66\x61lse\x12/\n\x0fpretrained_path\x18\x03 \x01(\t:\x16~/pretrained_backbones')
)




_BACKBONE = _descriptor.Descriptor(
  name='BackBone',
  full_name='BackBone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='BackBone.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_pretrained', full_name='BackBone.use_pretrained', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pretrained_path', full_name='BackBone.pretrained_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("~/pretrained_backbones").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['BackBone'] = _BACKBONE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BackBone = _reflection.GeneratedProtocolMessageType('BackBone', (_message.Message,), {
  'DESCRIPTOR' : _BACKBONE,
  '__module__' : 'protos.backbones_pb2'
  # @@protoc_insertion_point(class_scope:BackBone)
  })
_sym_db.RegisterMessage(BackBone)


# @@protoc_insertion_point(module_scope)
