# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/learning_rates.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/learning_rates.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1bprotos/learning_rates.proto\"\x9d\x02\n\x11LearningRateDecay\x12.\n\x11\x65xponential_decay\x18\x01 \x01(\x0b\x32\x11.ExponentialDecayH\x00\x12.\n\x11inversetime_decay\x18\x02 \x01(\x0b\x32\x11.InverseTimeDecayH\x00\x12:\n\x17piecewiseconstant_decay\x18\x03 \x01(\x0b\x32\x17.PiecewiseConstantDecayH\x00\x12,\n\x10polynomial_decay\x18\x04 \x01(\x0b\x32\x10.PolynomialDecayH\x00\x12&\n\rconstant_rate\x18\x05 \x01(\x0b\x32\r.ConstantRateH\x00\x42\x16\n\x14LearningRateSchedule\"t\n\x10\x45xponentialDecay\x12\x1d\n\x15initial_learning_rate\x18\x01 \x02(\x02\x12\x13\n\x0b\x64\x65\x63\x61y_steps\x18\x02 \x02(\x03\x12\x12\n\ndecay_rate\x18\x03 \x02(\x02\x12\x18\n\tstaircase\x18\x04 \x01(\x08:\x05\x66\x61lse\"t\n\x10InverseTimeDecay\x12\x1d\n\x15initial_learning_rate\x18\x01 \x02(\x02\x12\x13\n\x0b\x64\x65\x63\x61y_steps\x18\x02 \x02(\x03\x12\x12\n\ndecay_rate\x18\x03 \x02(\x02\x12\x18\n\tstaircase\x18\x04 \x01(\x08:\x05\x66\x61lse\"<\n\x16PiecewiseConstantDecay\x12\x12\n\nboundaries\x18\x01 \x03(\x03\x12\x0e\n\x06values\x18\x02 \x03(\x02\"\x90\x01\n\x0fPolynomialDecay\x12\x1d\n\x15initial_learning_rate\x18\x01 \x02(\x02\x12\x13\n\x0b\x64\x65\x63\x61y_steps\x18\x02 \x02(\x03\x12!\n\x11\x65nd_learning_rate\x18\x03 \x01(\x02:\x06\x30.0001\x12\x10\n\x05power\x18\x04 \x01(\x02:\x01\x31\x12\x14\n\x05\x63ycle\x18\x05 \x01(\x08:\x05\x66\x61lse\"%\n\x0c\x43onstantRate\x12\x15\n\rlearning_rate\x18\x01 \x02(\x02')
)




_LEARNINGRATEDECAY = _descriptor.Descriptor(
  name='LearningRateDecay',
  full_name='LearningRateDecay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exponential_decay', full_name='LearningRateDecay.exponential_decay', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inversetime_decay', full_name='LearningRateDecay.inversetime_decay', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='piecewiseconstant_decay', full_name='LearningRateDecay.piecewiseconstant_decay', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='polynomial_decay', full_name='LearningRateDecay.polynomial_decay', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='constant_rate', full_name='LearningRateDecay.constant_rate', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='LearningRateSchedule', full_name='LearningRateDecay.LearningRateSchedule',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=32,
  serialized_end=317,
)


_EXPONENTIALDECAY = _descriptor.Descriptor(
  name='ExponentialDecay',
  full_name='ExponentialDecay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='initial_learning_rate', full_name='ExponentialDecay.initial_learning_rate', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decay_steps', full_name='ExponentialDecay.decay_steps', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decay_rate', full_name='ExponentialDecay.decay_rate', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='staircase', full_name='ExponentialDecay.staircase', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=435,
)


_INVERSETIMEDECAY = _descriptor.Descriptor(
  name='InverseTimeDecay',
  full_name='InverseTimeDecay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='initial_learning_rate', full_name='InverseTimeDecay.initial_learning_rate', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decay_steps', full_name='InverseTimeDecay.decay_steps', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decay_rate', full_name='InverseTimeDecay.decay_rate', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='staircase', full_name='InverseTimeDecay.staircase', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=553,
)


_PIECEWISECONSTANTDECAY = _descriptor.Descriptor(
  name='PiecewiseConstantDecay',
  full_name='PiecewiseConstantDecay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='boundaries', full_name='PiecewiseConstantDecay.boundaries', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='PiecewiseConstantDecay.values', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=555,
  serialized_end=615,
)


_POLYNOMIALDECAY = _descriptor.Descriptor(
  name='PolynomialDecay',
  full_name='PolynomialDecay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='initial_learning_rate', full_name='PolynomialDecay.initial_learning_rate', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decay_steps', full_name='PolynomialDecay.decay_steps', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_learning_rate', full_name='PolynomialDecay.end_learning_rate', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.0001),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='power', full_name='PolynomialDecay.power', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cycle', full_name='PolynomialDecay.cycle', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=618,
  serialized_end=762,
)


_CONSTANTRATE = _descriptor.Descriptor(
  name='ConstantRate',
  full_name='ConstantRate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='ConstantRate.learning_rate', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=764,
  serialized_end=801,
)

_LEARNINGRATEDECAY.fields_by_name['exponential_decay'].message_type = _EXPONENTIALDECAY
_LEARNINGRATEDECAY.fields_by_name['inversetime_decay'].message_type = _INVERSETIMEDECAY
_LEARNINGRATEDECAY.fields_by_name['piecewiseconstant_decay'].message_type = _PIECEWISECONSTANTDECAY
_LEARNINGRATEDECAY.fields_by_name['polynomial_decay'].message_type = _POLYNOMIALDECAY
_LEARNINGRATEDECAY.fields_by_name['constant_rate'].message_type = _CONSTANTRATE
_LEARNINGRATEDECAY.oneofs_by_name['LearningRateSchedule'].fields.append(
  _LEARNINGRATEDECAY.fields_by_name['exponential_decay'])
_LEARNINGRATEDECAY.fields_by_name['exponential_decay'].containing_oneof = _LEARNINGRATEDECAY.oneofs_by_name['LearningRateSchedule']
_LEARNINGRATEDECAY.oneofs_by_name['LearningRateSchedule'].fields.append(
  _LEARNINGRATEDECAY.fields_by_name['inversetime_decay'])
_LEARNINGRATEDECAY.fields_by_name['inversetime_decay'].containing_oneof = _LEARNINGRATEDECAY.oneofs_by_name['LearningRateSchedule']
_LEARNINGRATEDECAY.oneofs_by_name['LearningRateSchedule'].fields.append(
  _LEARNINGRATEDECAY.fields_by_name['piecewiseconstant_decay'])
_LEARNINGRATEDECAY.fields_by_name['piecewiseconstant_decay'].containing_oneof = _LEARNINGRATEDECAY.oneofs_by_name['LearningRateSchedule']
_LEARNINGRATEDECAY.oneofs_by_name['LearningRateSchedule'].fields.append(
  _LEARNINGRATEDECAY.fields_by_name['polynomial_decay'])
_LEARNINGRATEDECAY.fields_by_name['polynomial_decay'].containing_oneof = _LEARNINGRATEDECAY.oneofs_by_name['LearningRateSchedule']
_LEARNINGRATEDECAY.oneofs_by_name['LearningRateSchedule'].fields.append(
  _LEARNINGRATEDECAY.fields_by_name['constant_rate'])
_LEARNINGRATEDECAY.fields_by_name['constant_rate'].containing_oneof = _LEARNINGRATEDECAY.oneofs_by_name['LearningRateSchedule']
DESCRIPTOR.message_types_by_name['LearningRateDecay'] = _LEARNINGRATEDECAY
DESCRIPTOR.message_types_by_name['ExponentialDecay'] = _EXPONENTIALDECAY
DESCRIPTOR.message_types_by_name['InverseTimeDecay'] = _INVERSETIMEDECAY
DESCRIPTOR.message_types_by_name['PiecewiseConstantDecay'] = _PIECEWISECONSTANTDECAY
DESCRIPTOR.message_types_by_name['PolynomialDecay'] = _POLYNOMIALDECAY
DESCRIPTOR.message_types_by_name['ConstantRate'] = _CONSTANTRATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LearningRateDecay = _reflection.GeneratedProtocolMessageType('LearningRateDecay', (_message.Message,), {
  'DESCRIPTOR' : _LEARNINGRATEDECAY,
  '__module__' : 'protos.learning_rates_pb2'
  # @@protoc_insertion_point(class_scope:LearningRateDecay)
  })
_sym_db.RegisterMessage(LearningRateDecay)

ExponentialDecay = _reflection.GeneratedProtocolMessageType('ExponentialDecay', (_message.Message,), {
  'DESCRIPTOR' : _EXPONENTIALDECAY,
  '__module__' : 'protos.learning_rates_pb2'
  # @@protoc_insertion_point(class_scope:ExponentialDecay)
  })
_sym_db.RegisterMessage(ExponentialDecay)

InverseTimeDecay = _reflection.GeneratedProtocolMessageType('InverseTimeDecay', (_message.Message,), {
  'DESCRIPTOR' : _INVERSETIMEDECAY,
  '__module__' : 'protos.learning_rates_pb2'
  # @@protoc_insertion_point(class_scope:InverseTimeDecay)
  })
_sym_db.RegisterMessage(InverseTimeDecay)

PiecewiseConstantDecay = _reflection.GeneratedProtocolMessageType('PiecewiseConstantDecay', (_message.Message,), {
  'DESCRIPTOR' : _PIECEWISECONSTANTDECAY,
  '__module__' : 'protos.learning_rates_pb2'
  # @@protoc_insertion_point(class_scope:PiecewiseConstantDecay)
  })
_sym_db.RegisterMessage(PiecewiseConstantDecay)

PolynomialDecay = _reflection.GeneratedProtocolMessageType('PolynomialDecay', (_message.Message,), {
  'DESCRIPTOR' : _POLYNOMIALDECAY,
  '__module__' : 'protos.learning_rates_pb2'
  # @@protoc_insertion_point(class_scope:PolynomialDecay)
  })
_sym_db.RegisterMessage(PolynomialDecay)

ConstantRate = _reflection.GeneratedProtocolMessageType('ConstantRate', (_message.Message,), {
  'DESCRIPTOR' : _CONSTANTRATE,
  '__module__' : 'protos.learning_rates_pb2'
  # @@protoc_insertion_point(class_scope:ConstantRate)
  })
_sym_db.RegisterMessage(ConstantRate)


# @@protoc_insertion_point(module_scope)
